### ISSUE TITLE
Wrong package name in docs

### ISSUE THREAD

**Issue by thalesog** [castle/castle-react-native#39]
Hello everyone!

I'm testing your library and found a typo error in [React Native Tutorial](https://docs.castle.io/v1/tutorials/client-side-integration/react-native/) page, inside your docs. 

![castle_docs_typo](https://user-images.githubusercontent.com/4792793/133491099-f47e58d9-fea3-4a96-afbf-b5364639e732.png)

It's missing the `l` from `@castleio`.

Taking advantage of the opportunity, I'm really enjoying your software and I intend to continue using it. 
Keep up with the good work guys!

**Comment by sebastiansimson** [comment]
Thank you for reporting this @thalesog, and thank you for the kind words. I'll make sure that this is corrected and close the issue once its published.

**Comment by davidwico** [comment]
@sebastiansimson The issue still persists, https://docs.castle.io/docs/sdk-mobile in Configuration / React Native tab

**Comment by wallin** [comment]
Thank you for reporting @davidwico, this has been corrected now
